<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
	  <ImplicitUsings>enable</ImplicitUsings>
	  <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Common\ValidationBase\**" />
    <EmbeddedResource Remove="Common\ValidationBase\**" />
    <None Remove="Common\ValidationBase\**" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CleanArc.Domain\CleanArc.Domain.csproj" />
    <PackageReference Include="Dapper" Version="2.1.24" />
    <PackageReference Include="Mapster" Version="7.4.0" />
    <PackageReference Include="Mapster.DependencyInjection" Version="1.0.1" />
    <PackageReference Include="Mediator.SourceGenerator" Version="2.1.1">
	    <PrivateAssets>all</PrivateAssets>
	    <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Mediator.Abstractions" Version="2.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Abstractions" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.2.5" />
    <PackageReference Include="System.Linq.Async" Version="6.0.1" />
	  <PackageReference Include="System.Runtime.Handles" Version="4.3.0" />
	  <PackageReference Include="System.IO.FileSystem.Primitives" Version="4.3.0" />
	  <PackageReference Include="System.Runtime.InteropServices" Version="4.3.0" />
	  <PackageReference Include="System.Diagnostics.Debug" Version="4.3.0" />
	  <PackageReference Include="System.Collections" Version="4.3.0" />
	  <PackageReference Include="System.Runtime.Extensions" Version="4.3.0" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Features\Auth\Commands\" />
  </ItemGroup>

</Project>
