<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
	  <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.24" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="7.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="7.0.3">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="System.Data.SqlClient" Version="4.8.6" />
    <PackageReference Include="Twilio" Version="7.11.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\CleanArc.Application\CleanArc.Application.csproj" />
    <ProjectReference Include="..\..\Core\CleanArc.Domain\CleanArc.Domain.csproj" />
    <ProjectReference Include="..\CleanArc.Infrastructure.Sql\CleanArc.Infrastructure.Sql.csproj" />
  </ItemGroup>

</Project>
